// Generated by tools/board_registry.py. Edit config/boards.json.
package com.silentwolf75.aethermesh.data

object BoardRegistry {
    data class Board(val id: String, val env: String, val updateFormat: String,
                     val modelAliases: List<String>, val fileAliases: List<String>)
    val boards = listOf(
        Board("heltec-v3", "heltec_v3", "esp-bin", listOf("heltec v3", "heltec-v3"), listOf("heltec-v3")),
        Board("heltec-v4", "heltec_v4", "esp-bin", listOf("heltec"), listOf("heltec-v4")),
        Board("t-deck", "lilygo_t_deck", "esp-bin", listOf("t-deck", "tdeck"), listOf("t-deck", "tdeck")),
        Board("crowpanel-35", "elecrow_crowpanel_35", "esp-bin", listOf("crowpanel"), listOf("crowpanel")),
        Board("seeed-t1000-e", "seeed_t1000_e", "nordic-dfu", listOf("t1000"), listOf("t1000")),
        Board("lilygo-t-echo", "lilygo_t_echo", "nordic-dfu", listOf("t-echo", "techo"), listOf("t-echo", "techo")),
        Board("rak19026", "rak19026", "nordic-dfu", listOf("19026"), listOf("19026")),
        Board("rak3401-1w", "rak3401_1w", "nordic-dfu", listOf("3401", "rak 1w"), listOf("rak3401")),
        Board("rak4631", "rak4631", "nordic-dfu", listOf("rak", "wisblock"), listOf("rak4631")),
    )
    private fun normalized(value: String) = value.lowercase().replace('_', '-')
    fun forModel(model: String?): Board? {
        val value = normalized(model.orEmpty())
        return boards.firstOrNull { board -> board.modelAliases.any { alias -> alias.split(" ").all { value.contains(it) } } }
    }
    fun forId(id: String?): Board? = boards.firstOrNull { it.id.equals(id, ignoreCase = true) }
    fun forFile(file: String): Board? {
        val value = normalized(file)
        return boards.firstOrNull { board ->
            value.contains(normalized(board.env)) || board.fileAliases.any { value.contains(it) }
        }
    }
}
