/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "mesh.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(aethermesh_MeshPacket, aethermesh_MeshPacket, 2)


PB_BIND(aethermesh_OtaControl, aethermesh_OtaControl, AUTO)


PB_BIND(aethermesh_OtaData, aethermesh_OtaData, AUTO)


PB_BIND(aethermesh_OtaStatus, aethermesh_OtaStatus, AUTO)


PB_BIND(aethermesh_TextMessage, aethermesh_TextMessage, AUTO)


PB_BIND(aethermesh_Telemetry, aethermesh_Telemetry, AUTO)


PB_BIND(aethermesh_RouteDiscovery, aethermesh_RouteDiscovery, AUTO)


PB_BIND(aethermesh_Ack, aethermesh_Ack, AUTO)


PB_BIND(aethermesh_DeliveryStatus, aethermesh_DeliveryStatus, AUTO)


PB_BIND(aethermesh_NodeConfig, aethermesh_NodeConfig, AUTO)


PB_BIND(aethermesh_AuthRequest, aethermesh_AuthRequest, AUTO)


PB_BIND(aethermesh_AuthResponse, aethermesh_AuthResponse, AUTO)













