/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AETHERMESH_MESH_PB_H_INCLUDED
#define PB_AETHERMESH_MESH_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aethermesh_OtaControl_Op {
    aethermesh_OtaControl_Op_BEGIN = 0,
    aethermesh_OtaControl_Op_END = 1,
    aethermesh_OtaControl_Op_ABORT = 2,
    aethermesh_OtaControl_Op_ENTER_DFU = 3 /* nRF52/RAK: reboot into the Adafruit/Nordic DFU bootloader; */
} aethermesh_OtaControl_Op;

typedef enum _aethermesh_OtaStatus_State {
    aethermesh_OtaStatus_State_IDLE = 0,
    aethermesh_OtaStatus_State_READY = 1, /* BEGIN accepted, send data */
    aethermesh_OtaStatus_State_IN_PROGRESS = 2, /* periodic ack; next_offset = bytes flashed so far */
    aethermesh_OtaStatus_State_SUCCESS = 3, /* image verified, rebooting */
    aethermesh_OtaStatus_State_ERROR = 4 /* aborted; message says why */
} aethermesh_OtaStatus_State;

typedef enum _aethermesh_RouteDiscovery_Type {
    aethermesh_RouteDiscovery_Type_REQUEST = 0,
    aethermesh_RouteDiscovery_Type_REPLY = 1
} aethermesh_RouteDiscovery_Type;

typedef enum _aethermesh_DeliveryStatus_State {
    aethermesh_DeliveryStatus_State_UNKNOWN = 0,
    aethermesh_DeliveryStatus_State_DELIVERED = 1,
    aethermesh_DeliveryStatus_State_FAILED = 2,
    aethermesh_DeliveryStatus_State_RETRYING = 3
} aethermesh_DeliveryStatus_State;

typedef enum _aethermesh_DeliveryStatus_Reason {
    aethermesh_DeliveryStatus_Reason_REASON_UNSPECIFIED = 0,
    aethermesh_DeliveryStatus_Reason_ACK_TIMEOUT = 1,
    aethermesh_DeliveryStatus_Reason_QUEUE_EVICTED = 2,
    aethermesh_DeliveryStatus_Reason_LOCAL_SEND_FAILED = 3
} aethermesh_DeliveryStatus_Reason;

/* Struct definitions */
typedef struct _aethermesh_OtaControl {
    aethermesh_OtaControl_Op op;
    uint32_t total_size; /* firmware image size in bytes (BEGIN) */
    char md5[33]; /* hex MD5 of the full image (BEGIN) */
} aethermesh_OtaControl;

typedef PB_BYTES_ARRAY_T(224) aethermesh_OtaData_data_t;
typedef struct _aethermesh_OtaData {
    uint32_t offset; /* byte offset of this chunk; must be sequential */
    aethermesh_OtaData_data_t data; /* chunk payload (max 192 bytes, see mesh.options) */
} aethermesh_OtaData;

typedef struct _aethermesh_OtaStatus {
    aethermesh_OtaStatus_State state;
    uint32_t next_offset;
    char message[40];
} aethermesh_OtaStatus;

/* Standard chat text message */
typedef struct _aethermesh_TextMessage {
    char content[168];
    char channel[32]; /* Target channel name (default: "General") */
    bool is_encrypted; /* True if content is encrypted */
} aethermesh_TextMessage;

/* Telemetry information periodically broadcasted by nodes */
typedef struct _aethermesh_Telemetry {
    uint32_t battery_level; /* 0 - 100% */
    float latitude; /* Latitude (degrees) */
    float longitude; /* Longitude (degrees) */
    int32_t altitude; /* Altitude (meters) */
    char node_model[32]; /* Board name/model (e.g. "Heltec V4") */
    uint32_t uptime_seconds; /* Seconds since the node booted */
    char firmware_version[20]; /* Firmware version string (e.g. "1.2.0") */
    bool is_charging; /* True when the battery is charging (voltage rising / on solar) */
    float battery_voltage; /* Raw pack voltage (V); 0 if unmeasured. For solar monitoring. */
    uint32_t position_precision; /* Privacy blur radius (meters) applied to lat/lon before */
} aethermesh_Telemetry;

/* Path discovery for unicast routing */
typedef struct _aethermesh_RouteDiscovery {
    aethermesh_RouteDiscovery_Type type;
    uint32_t target_id; /* The node we want to find a route to */
    uint32_t metric; /* Hop count or link cost */
} aethermesh_RouteDiscovery;

/* Acknowledgment for reliable packet delivery */
typedef struct _aethermesh_Ack {
    uint32_t acked_packet_id;
    float acked_rx_rssi; /* RSSI (dBm) at which the ACKing node heard the acked packet. */
    /* Gives the sender the outbound link quality; 0 = not reported. */
    float acked_rx_snr; /* SNR (dB) at which the ACKing node heard the acked packet */
} aethermesh_Ack;

/* Local delivery lifecycle event from a connected node to the companion app.
 These events are sent over BLE only; they are not routed over LoRa. */
typedef struct _aethermesh_DeliveryStatus {
    uint32_t packet_id;
    uint32_t recipient_id;
    aethermesh_DeliveryStatus_State state;
    aethermesh_DeliveryStatus_Reason reason;
    uint32_t retry_count;
} aethermesh_DeliveryStatus;

/* Configuration settings sync */
typedef struct _aethermesh_NodeConfig {
    char node_name[17]; /* Custom name (max size 16 characters) */
    uint32_t lora_sf; /* 7 to 12 */
    float lora_bw; /* 125.0, 250.0, 500.0 */
    int32_t lora_tx_power; /* 10 to 22 (up to 30 for 1W) */
    uint32_t region; /* 0 = US915, 1 = EU868 */
    uint32_t node_role; /* 0 = Client, 1 = Router, 2 = Low-Power Repeater */
    uint32_t telemetry_interval; /* In seconds */
    uint32_t screen_timeout_secs; /* Screen timeout in seconds (0 = display always off, 0xFFFFFFFF = display always on, default/standard is 30s) */
    bool power_save_mode; /* Auto sleep, lower telemetry, reduce BLE advertising when low battery */
    char config_password[33]; /* Node admin password authorizing a remote (over-LoRa) config change. */
    /* Empty for local BLE config (the BLE session is already authenticated). */
    uint32_t position_precision; /* Privacy blur radius (meters) for broadcast positions; 0 = precise. */
    uint32_t gps_mode; /* 0 = onboard GPS powered (default), 1 = GPS off to save power */
    /* (position falls back to phone-shared GPS). uint32 so the
 proto3 zero-default means "on" for configs that omit it. */
    bool fixed_position; /* True if using a static fixed position instead of GPS */
    float fixed_latitude; /* Static latitude */
    float fixed_longitude; /* Static longitude */
    int32_t fixed_altitude; /* Static altitude */
} aethermesh_NodeConfig;

/* Authentication request sent by companion app to LoRa node */
typedef struct _aethermesh_AuthRequest {
    char password[32];
    bool is_change_password;
    char new_password[32];
} aethermesh_AuthRequest;

/* Authentication response returned by LoRa node to companion app */
typedef struct _aethermesh_AuthResponse {
    bool success;
    char message[32];
    bool password_not_set;
} aethermesh_AuthResponse;

/* Wrapper for all packets sent over LoRa or BLE */
typedef struct _aethermesh_MeshPacket {
    uint32_t sender_id; /* Unique 32-bit ID (derived from MCU MAC address) */
    uint32_t recipient_id; /* Recipient ID (0xFFFFFFFF for broadcast) */
    uint32_t packet_id; /* Sequence number generated by sender */
    uint32_t hop_limit; /* Remaining hops allowed */
    bool want_ack; /* True if sender requests an ACK */
    pb_size_t which_payload;
    union {
        aethermesh_TextMessage text;
        aethermesh_Telemetry telemetry;
        aethermesh_RouteDiscovery route_discovery;
        aethermesh_Ack ack;
        aethermesh_NodeConfig config;
        aethermesh_AuthRequest auth_request;
        aethermesh_AuthResponse auth_response;
        aethermesh_DeliveryStatus delivery_status;
        aethermesh_OtaControl ota_control;
        aethermesh_OtaData ota_data;
        aethermesh_OtaStatus ota_status;
    } payload;
    uint32_t prev_hop_id; /* The node that just transmitted/relayed this packet */
    float rx_rssi; /* Received Signal Strength Indicator (LoRa last hop) */
    float rx_snr; /* Signal-to-Noise Ratio (LoRa last hop) */
    uint32_t retry_count; /* Retransmit attempt for this packet_id; relays forward higher attempts. */
} aethermesh_MeshPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aethermesh_OtaControl_Op_MIN aethermesh_OtaControl_Op_BEGIN
#define _aethermesh_OtaControl_Op_MAX aethermesh_OtaControl_Op_ENTER_DFU
#define _aethermesh_OtaControl_Op_ARRAYSIZE ((aethermesh_OtaControl_Op)(aethermesh_OtaControl_Op_ENTER_DFU+1))

#define _aethermesh_OtaStatus_State_MIN aethermesh_OtaStatus_State_IDLE
#define _aethermesh_OtaStatus_State_MAX aethermesh_OtaStatus_State_ERROR
#define _aethermesh_OtaStatus_State_ARRAYSIZE ((aethermesh_OtaStatus_State)(aethermesh_OtaStatus_State_ERROR+1))

#define _aethermesh_RouteDiscovery_Type_MIN aethermesh_RouteDiscovery_Type_REQUEST
#define _aethermesh_RouteDiscovery_Type_MAX aethermesh_RouteDiscovery_Type_REPLY
#define _aethermesh_RouteDiscovery_Type_ARRAYSIZE ((aethermesh_RouteDiscovery_Type)(aethermesh_RouteDiscovery_Type_REPLY+1))

#define _aethermesh_DeliveryStatus_State_MIN aethermesh_DeliveryStatus_State_UNKNOWN
#define _aethermesh_DeliveryStatus_State_MAX aethermesh_DeliveryStatus_State_RETRYING
#define _aethermesh_DeliveryStatus_State_ARRAYSIZE ((aethermesh_DeliveryStatus_State)(aethermesh_DeliveryStatus_State_RETRYING+1))

#define _aethermesh_DeliveryStatus_Reason_MIN aethermesh_DeliveryStatus_Reason_REASON_UNSPECIFIED
#define _aethermesh_DeliveryStatus_Reason_MAX aethermesh_DeliveryStatus_Reason_LOCAL_SEND_FAILED
#define _aethermesh_DeliveryStatus_Reason_ARRAYSIZE ((aethermesh_DeliveryStatus_Reason)(aethermesh_DeliveryStatus_Reason_LOCAL_SEND_FAILED+1))


#define aethermesh_OtaControl_op_ENUMTYPE aethermesh_OtaControl_Op


#define aethermesh_OtaStatus_state_ENUMTYPE aethermesh_OtaStatus_State



#define aethermesh_RouteDiscovery_type_ENUMTYPE aethermesh_RouteDiscovery_Type


#define aethermesh_DeliveryStatus_state_ENUMTYPE aethermesh_DeliveryStatus_State
#define aethermesh_DeliveryStatus_reason_ENUMTYPE aethermesh_DeliveryStatus_Reason





/* Initializer values for message structs */
#define aethermesh_MeshPacket_init_default       {0, 0, 0, 0, 0, 0, {aethermesh_TextMessage_init_default}, 0, 0, 0, 0}
#define aethermesh_OtaControl_init_default       {_aethermesh_OtaControl_Op_MIN, 0, ""}
#define aethermesh_OtaData_init_default          {0, {0, {0}}}
#define aethermesh_OtaStatus_init_default        {_aethermesh_OtaStatus_State_MIN, 0, ""}
#define aethermesh_TextMessage_init_default      {"", "", 0}
#define aethermesh_Telemetry_init_default        {0, 0, 0, 0, "", 0, "", 0, 0, 0}
#define aethermesh_RouteDiscovery_init_default   {_aethermesh_RouteDiscovery_Type_MIN, 0, 0}
#define aethermesh_Ack_init_default              {0, 0, 0}
#define aethermesh_DeliveryStatus_init_default   {0, 0, _aethermesh_DeliveryStatus_State_MIN, _aethermesh_DeliveryStatus_Reason_MIN, 0}
#define aethermesh_NodeConfig_init_default       {"", 0, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0}
#define aethermesh_AuthRequest_init_default      {"", 0, ""}
#define aethermesh_AuthResponse_init_default     {0, "", 0}
#define aethermesh_MeshPacket_init_zero          {0, 0, 0, 0, 0, 0, {aethermesh_TextMessage_init_zero}, 0, 0, 0, 0}
#define aethermesh_OtaControl_init_zero          {_aethermesh_OtaControl_Op_MIN, 0, ""}
#define aethermesh_OtaData_init_zero             {0, {0, {0}}}
#define aethermesh_OtaStatus_init_zero           {_aethermesh_OtaStatus_State_MIN, 0, ""}
#define aethermesh_TextMessage_init_zero         {"", "", 0}
#define aethermesh_Telemetry_init_zero           {0, 0, 0, 0, "", 0, "", 0, 0, 0}
#define aethermesh_RouteDiscovery_init_zero      {_aethermesh_RouteDiscovery_Type_MIN, 0, 0}
#define aethermesh_Ack_init_zero                 {0, 0, 0}
#define aethermesh_DeliveryStatus_init_zero      {0, 0, _aethermesh_DeliveryStatus_State_MIN, _aethermesh_DeliveryStatus_Reason_MIN, 0}
#define aethermesh_NodeConfig_init_zero          {"", 0, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0}
#define aethermesh_AuthRequest_init_zero         {"", 0, ""}
#define aethermesh_AuthResponse_init_zero        {0, "", 0}

/* Field tags (for use in manual encoding/decoding) */
#define aethermesh_OtaControl_op_tag             1
#define aethermesh_OtaControl_total_size_tag     2
#define aethermesh_OtaControl_md5_tag            3
#define aethermesh_OtaData_offset_tag            1
#define aethermesh_OtaData_data_tag              2
#define aethermesh_OtaStatus_state_tag           1
#define aethermesh_OtaStatus_next_offset_tag     2
#define aethermesh_OtaStatus_message_tag         3
#define aethermesh_TextMessage_content_tag       1
#define aethermesh_TextMessage_channel_tag       2
#define aethermesh_TextMessage_is_encrypted_tag  3
#define aethermesh_Telemetry_battery_level_tag   1
#define aethermesh_Telemetry_latitude_tag        2
#define aethermesh_Telemetry_longitude_tag       3
#define aethermesh_Telemetry_altitude_tag        4
#define aethermesh_Telemetry_node_model_tag      5
#define aethermesh_Telemetry_uptime_seconds_tag  6
#define aethermesh_Telemetry_firmware_version_tag 7
#define aethermesh_Telemetry_is_charging_tag     8
#define aethermesh_Telemetry_battery_voltage_tag 9
#define aethermesh_Telemetry_position_precision_tag 10
#define aethermesh_RouteDiscovery_type_tag       1
#define aethermesh_RouteDiscovery_target_id_tag  2
#define aethermesh_RouteDiscovery_metric_tag     3
#define aethermesh_Ack_acked_packet_id_tag       1
#define aethermesh_Ack_acked_rx_rssi_tag         2
#define aethermesh_Ack_acked_rx_snr_tag          3
#define aethermesh_DeliveryStatus_packet_id_tag  1
#define aethermesh_DeliveryStatus_recipient_id_tag 2
#define aethermesh_DeliveryStatus_state_tag      3
#define aethermesh_DeliveryStatus_reason_tag     4
#define aethermesh_DeliveryStatus_retry_count_tag 5
#define aethermesh_NodeConfig_node_name_tag      1
#define aethermesh_NodeConfig_lora_sf_tag        2
#define aethermesh_NodeConfig_lora_bw_tag        3
#define aethermesh_NodeConfig_lora_tx_power_tag  4
#define aethermesh_NodeConfig_region_tag         5
#define aethermesh_NodeConfig_node_role_tag      6
#define aethermesh_NodeConfig_telemetry_interval_tag 7
#define aethermesh_NodeConfig_screen_timeout_secs_tag 8
#define aethermesh_NodeConfig_power_save_mode_tag 9
#define aethermesh_NodeConfig_config_password_tag 10
#define aethermesh_NodeConfig_position_precision_tag 11
#define aethermesh_NodeConfig_gps_mode_tag       12
#define aethermesh_NodeConfig_fixed_position_tag 13
#define aethermesh_NodeConfig_fixed_latitude_tag 14
#define aethermesh_NodeConfig_fixed_longitude_tag 15
#define aethermesh_NodeConfig_fixed_altitude_tag 16
#define aethermesh_AuthRequest_password_tag      1
#define aethermesh_AuthRequest_is_change_password_tag 2
#define aethermesh_AuthRequest_new_password_tag  3
#define aethermesh_AuthResponse_success_tag      1
#define aethermesh_AuthResponse_message_tag      2
#define aethermesh_AuthResponse_password_not_set_tag 3
#define aethermesh_MeshPacket_sender_id_tag      1
#define aethermesh_MeshPacket_recipient_id_tag   2
#define aethermesh_MeshPacket_packet_id_tag      3
#define aethermesh_MeshPacket_hop_limit_tag      4
#define aethermesh_MeshPacket_want_ack_tag       5
#define aethermesh_MeshPacket_text_tag           6
#define aethermesh_MeshPacket_telemetry_tag      7
#define aethermesh_MeshPacket_route_discovery_tag 8
#define aethermesh_MeshPacket_ack_tag            9
#define aethermesh_MeshPacket_config_tag         11
#define aethermesh_MeshPacket_auth_request_tag   12
#define aethermesh_MeshPacket_auth_response_tag  13
#define aethermesh_MeshPacket_delivery_status_tag 17
#define aethermesh_MeshPacket_ota_control_tag    18
#define aethermesh_MeshPacket_ota_data_tag       19
#define aethermesh_MeshPacket_ota_status_tag     20
#define aethermesh_MeshPacket_prev_hop_id_tag    10
#define aethermesh_MeshPacket_rx_rssi_tag        14
#define aethermesh_MeshPacket_rx_snr_tag         15
#define aethermesh_MeshPacket_retry_count_tag    16

/* Struct field encoding specification for nanopb */
#define aethermesh_MeshPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sender_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   recipient_id,      2) \
X(a, STATIC,   SINGULAR, UINT32,   packet_id,         3) \
X(a, STATIC,   SINGULAR, UINT32,   hop_limit,         4) \
X(a, STATIC,   SINGULAR, BOOL,     want_ack,          5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,text,payload.text),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,telemetry,payload.telemetry),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,route_discovery,payload.route_discovery),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ack,payload.ack),   9) \
X(a, STATIC,   SINGULAR, UINT32,   prev_hop_id,      10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,config,payload.config),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,auth_request,payload.auth_request),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,auth_response,payload.auth_response),  13) \
X(a, STATIC,   SINGULAR, FLOAT,    rx_rssi,          14) \
X(a, STATIC,   SINGULAR, FLOAT,    rx_snr,           15) \
X(a, STATIC,   SINGULAR, UINT32,   retry_count,      16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,delivery_status,payload.delivery_status),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ota_control,payload.ota_control),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ota_data,payload.ota_data),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ota_status,payload.ota_status),  20)
#define aethermesh_MeshPacket_CALLBACK NULL
#define aethermesh_MeshPacket_DEFAULT NULL
#define aethermesh_MeshPacket_payload_text_MSGTYPE aethermesh_TextMessage
#define aethermesh_MeshPacket_payload_telemetry_MSGTYPE aethermesh_Telemetry
#define aethermesh_MeshPacket_payload_route_discovery_MSGTYPE aethermesh_RouteDiscovery
#define aethermesh_MeshPacket_payload_ack_MSGTYPE aethermesh_Ack
#define aethermesh_MeshPacket_payload_config_MSGTYPE aethermesh_NodeConfig
#define aethermesh_MeshPacket_payload_auth_request_MSGTYPE aethermesh_AuthRequest
#define aethermesh_MeshPacket_payload_auth_response_MSGTYPE aethermesh_AuthResponse
#define aethermesh_MeshPacket_payload_delivery_status_MSGTYPE aethermesh_DeliveryStatus
#define aethermesh_MeshPacket_payload_ota_control_MSGTYPE aethermesh_OtaControl
#define aethermesh_MeshPacket_payload_ota_data_MSGTYPE aethermesh_OtaData
#define aethermesh_MeshPacket_payload_ota_status_MSGTYPE aethermesh_OtaStatus

#define aethermesh_OtaControl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    op,                1) \
X(a, STATIC,   SINGULAR, UINT32,   total_size,        2) \
X(a, STATIC,   SINGULAR, STRING,   md5,               3)
#define aethermesh_OtaControl_CALLBACK NULL
#define aethermesh_OtaControl_DEFAULT NULL

#define aethermesh_OtaData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            1) \
X(a, STATIC,   SINGULAR, BYTES,    data,              2)
#define aethermesh_OtaData_CALLBACK NULL
#define aethermesh_OtaData_DEFAULT NULL

#define aethermesh_OtaStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1) \
X(a, STATIC,   SINGULAR, UINT32,   next_offset,       2) \
X(a, STATIC,   SINGULAR, STRING,   message,           3)
#define aethermesh_OtaStatus_CALLBACK NULL
#define aethermesh_OtaStatus_DEFAULT NULL

#define aethermesh_TextMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   content,           1) \
X(a, STATIC,   SINGULAR, STRING,   channel,           2) \
X(a, STATIC,   SINGULAR, BOOL,     is_encrypted,      3)
#define aethermesh_TextMessage_CALLBACK NULL
#define aethermesh_TextMessage_DEFAULT NULL

#define aethermesh_Telemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   battery_level,     1) \
X(a, STATIC,   SINGULAR, FLOAT,    latitude,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    longitude,         3) \
X(a, STATIC,   SINGULAR, INT32,    altitude,          4) \
X(a, STATIC,   SINGULAR, STRING,   node_model,        5) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_seconds,    6) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   7) \
X(a, STATIC,   SINGULAR, BOOL,     is_charging,       8) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_voltage,   9) \
X(a, STATIC,   SINGULAR, UINT32,   position_precision,  10)
#define aethermesh_Telemetry_CALLBACK NULL
#define aethermesh_Telemetry_DEFAULT NULL

#define aethermesh_RouteDiscovery_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   target_id,         2) \
X(a, STATIC,   SINGULAR, UINT32,   metric,            3)
#define aethermesh_RouteDiscovery_CALLBACK NULL
#define aethermesh_RouteDiscovery_DEFAULT NULL

#define aethermesh_Ack_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   acked_packet_id,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    acked_rx_rssi,     2) \
X(a, STATIC,   SINGULAR, FLOAT,    acked_rx_snr,      3)
#define aethermesh_Ack_CALLBACK NULL
#define aethermesh_Ack_DEFAULT NULL

#define aethermesh_DeliveryStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   packet_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   recipient_id,      2) \
X(a, STATIC,   SINGULAR, UENUM,    state,             3) \
X(a, STATIC,   SINGULAR, UENUM,    reason,            4) \
X(a, STATIC,   SINGULAR, UINT32,   retry_count,       5)
#define aethermesh_DeliveryStatus_CALLBACK NULL
#define aethermesh_DeliveryStatus_DEFAULT NULL

#define aethermesh_NodeConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   node_name,         1) \
X(a, STATIC,   SINGULAR, UINT32,   lora_sf,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    lora_bw,           3) \
X(a, STATIC,   SINGULAR, INT32,    lora_tx_power,     4) \
X(a, STATIC,   SINGULAR, UINT32,   region,            5) \
X(a, STATIC,   SINGULAR, UINT32,   node_role,         6) \
X(a, STATIC,   SINGULAR, UINT32,   telemetry_interval,   7) \
X(a, STATIC,   SINGULAR, UINT32,   screen_timeout_secs,   8) \
X(a, STATIC,   SINGULAR, BOOL,     power_save_mode,   9) \
X(a, STATIC,   SINGULAR, STRING,   config_password,  10) \
X(a, STATIC,   SINGULAR, UINT32,   position_precision,  11) \
X(a, STATIC,   SINGULAR, UINT32,   gps_mode,         12) \
X(a, STATIC,   SINGULAR, BOOL,     fixed_position,   13) \
X(a, STATIC,   SINGULAR, FLOAT,    fixed_latitude,   14) \
X(a, STATIC,   SINGULAR, FLOAT,    fixed_longitude,  15) \
X(a, STATIC,   SINGULAR, INT32,    fixed_altitude,   16)
#define aethermesh_NodeConfig_CALLBACK NULL
#define aethermesh_NodeConfig_DEFAULT NULL

#define aethermesh_AuthRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   password,          1) \
X(a, STATIC,   SINGULAR, BOOL,     is_change_password,   2) \
X(a, STATIC,   SINGULAR, STRING,   new_password,      3)
#define aethermesh_AuthRequest_CALLBACK NULL
#define aethermesh_AuthRequest_DEFAULT NULL

#define aethermesh_AuthResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2) \
X(a, STATIC,   SINGULAR, BOOL,     password_not_set,   3)
#define aethermesh_AuthResponse_CALLBACK NULL
#define aethermesh_AuthResponse_DEFAULT NULL

extern const pb_msgdesc_t aethermesh_MeshPacket_msg;
extern const pb_msgdesc_t aethermesh_OtaControl_msg;
extern const pb_msgdesc_t aethermesh_OtaData_msg;
extern const pb_msgdesc_t aethermesh_OtaStatus_msg;
extern const pb_msgdesc_t aethermesh_TextMessage_msg;
extern const pb_msgdesc_t aethermesh_Telemetry_msg;
extern const pb_msgdesc_t aethermesh_RouteDiscovery_msg;
extern const pb_msgdesc_t aethermesh_Ack_msg;
extern const pb_msgdesc_t aethermesh_DeliveryStatus_msg;
extern const pb_msgdesc_t aethermesh_NodeConfig_msg;
extern const pb_msgdesc_t aethermesh_AuthRequest_msg;
extern const pb_msgdesc_t aethermesh_AuthResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aethermesh_MeshPacket_fields &aethermesh_MeshPacket_msg
#define aethermesh_OtaControl_fields &aethermesh_OtaControl_msg
#define aethermesh_OtaData_fields &aethermesh_OtaData_msg
#define aethermesh_OtaStatus_fields &aethermesh_OtaStatus_msg
#define aethermesh_TextMessage_fields &aethermesh_TextMessage_msg
#define aethermesh_Telemetry_fields &aethermesh_Telemetry_msg
#define aethermesh_RouteDiscovery_fields &aethermesh_RouteDiscovery_msg
#define aethermesh_Ack_fields &aethermesh_Ack_msg
#define aethermesh_DeliveryStatus_fields &aethermesh_DeliveryStatus_msg
#define aethermesh_NodeConfig_fields &aethermesh_NodeConfig_msg
#define aethermesh_AuthRequest_fields &aethermesh_AuthRequest_msg
#define aethermesh_AuthResponse_fields &aethermesh_AuthResponse_msg

/* Maximum encoded size of messages (where known) */
#define AETHERMESH_MESH_PB_H_MAX_SIZE            aethermesh_MeshPacket_size
#define aethermesh_Ack_size                      16
#define aethermesh_AuthRequest_size              68
#define aethermesh_AuthResponse_size             37
#define aethermesh_DeliveryStatus_size           22
#define aethermesh_MeshPacket_size               286
#define aethermesh_NodeConfig_size               136
#define aethermesh_OtaControl_size               42
#define aethermesh_OtaData_size                  233
#define aethermesh_OtaStatus_size                49
#define aethermesh_RouteDiscovery_size           14
#define aethermesh_Telemetry_size                100
#define aethermesh_TextMessage_size              205

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
