/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AETHERMESH_MESH_PB_H_INCLUDED
#define PB_AETHERMESH_MESH_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aethermesh_RouteDiscovery_Type {
    aethermesh_RouteDiscovery_Type_REQUEST = 0,
    aethermesh_RouteDiscovery_Type_REPLY = 1
} aethermesh_RouteDiscovery_Type;

/* Struct definitions */
/* Standard chat text message */
typedef struct _aethermesh_TextMessage {
    char content[168];
    char channel[32]; /* Target channel name (default: "General") */
    bool is_encrypted; /* True if content is encrypted */
} aethermesh_TextMessage;

/* Telemetry information periodically broadcasted by nodes */
typedef struct _aethermesh_Telemetry {
    uint32_t battery_level; /* 0 - 100% */
    float latitude; /* Latitude (degrees) */
    float longitude; /* Longitude (degrees) */
    int32_t altitude; /* Altitude (meters) */
    char node_model[32]; /* Board name/model (e.g. "Heltec V4") */
    uint32_t uptime_seconds; /* Seconds since the node booted */
    char firmware_version[12]; /* Firmware version string (e.g. "1.2.0") */
    bool is_charging; /* True when the battery is charging (voltage rising / on solar) */
} aethermesh_Telemetry;

/* Path discovery for unicast routing */
typedef struct _aethermesh_RouteDiscovery {
    aethermesh_RouteDiscovery_Type type;
    uint32_t target_id; /* The node we want to find a route to */
    uint32_t metric; /* Hop count or link cost */
} aethermesh_RouteDiscovery;

/* Acknowledgment for reliable packet delivery */
typedef struct _aethermesh_Ack {
    uint32_t acked_packet_id;
    float acked_rx_rssi; /* RSSI (dBm) at which the ACKing node heard the acked packet. */
    /* Gives the sender the outbound link quality; 0 = not reported. */
    float acked_rx_snr; /* SNR (dB) at which the ACKing node heard the acked packet */
} aethermesh_Ack;

/* Configuration settings sync */
typedef struct _aethermesh_NodeConfig {
    char node_name[17]; /* Custom name (max size 16 characters) */
    uint32_t lora_sf; /* 7 to 12 */
    float lora_bw; /* 125.0, 250.0, 500.0 */
    int32_t lora_tx_power; /* 10 to 22 (up to 30 for 1W) */
    uint32_t region; /* 0 = US915, 1 = EU868 */
    uint32_t node_role; /* 0 = Client, 1 = Router, 2 = Low-Power Repeater */
    uint32_t telemetry_interval; /* In seconds */
    uint32_t screen_timeout_secs; /* Screen timeout in seconds (0 = display always off, 0xFFFFFFFF = display always on, default/standard is 30s) */
    bool power_save_mode; /* Auto sleep, lower telemetry, reduce BLE advertising when low battery */
    char config_password[33]; /* Node admin password authorizing a remote (over-LoRa) config change. */
} aethermesh_NodeConfig;

/* Authentication request sent by companion app to LoRa node */
typedef struct _aethermesh_AuthRequest {
    char password[32];
    bool is_change_password;
    char new_password[32];
} aethermesh_AuthRequest;

/* Authentication response returned by LoRa node to companion app */
typedef struct _aethermesh_AuthResponse {
    bool success;
    char message[32];
    bool password_not_set;
} aethermesh_AuthResponse;

/* Wrapper for all packets sent over LoRa or BLE */
typedef struct _aethermesh_MeshPacket {
    uint32_t sender_id; /* Unique 32-bit ID (derived from MCU MAC address) */
    uint32_t recipient_id; /* Recipient ID (0xFFFFFFFF for broadcast) */
    uint32_t packet_id; /* Sequence number generated by sender */
    uint32_t hop_limit; /* Remaining hops allowed */
    bool want_ack; /* True if sender requests an ACK */
    pb_size_t which_payload;
    union {
        aethermesh_TextMessage text;
        aethermesh_Telemetry telemetry;
        aethermesh_RouteDiscovery route_discovery;
        aethermesh_Ack ack;
        aethermesh_NodeConfig config;
        aethermesh_AuthRequest auth_request;
        aethermesh_AuthResponse auth_response;
    } payload;
    uint32_t prev_hop_id; /* The node that just transmitted/relayed this packet */
    float rx_rssi; /* Received Signal Strength Indicator (LoRa last hop) */
    float rx_snr; /* Signal-to-Noise Ratio (LoRa last hop) */
} aethermesh_MeshPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aethermesh_RouteDiscovery_Type_MIN aethermesh_RouteDiscovery_Type_REQUEST
#define _aethermesh_RouteDiscovery_Type_MAX aethermesh_RouteDiscovery_Type_REPLY
#define _aethermesh_RouteDiscovery_Type_ARRAYSIZE ((aethermesh_RouteDiscovery_Type)(aethermesh_RouteDiscovery_Type_REPLY+1))




#define aethermesh_RouteDiscovery_type_ENUMTYPE aethermesh_RouteDiscovery_Type






/* Initializer values for message structs */
#define aethermesh_MeshPacket_init_default       {0, 0, 0, 0, 0, 0, {aethermesh_TextMessage_init_default}, 0, 0, 0}
#define aethermesh_TextMessage_init_default      {"", "", 0}
#define aethermesh_Telemetry_init_default        {0, 0, 0, 0, "", 0, "", 0}
#define aethermesh_RouteDiscovery_init_default   {_aethermesh_RouteDiscovery_Type_MIN, 0, 0}
#define aethermesh_Ack_init_default              {0, 0, 0}
#define aethermesh_NodeConfig_init_default       {"", 0, 0, 0, 0, 0, 0, 0, 0, ""}
#define aethermesh_AuthRequest_init_default      {"", 0, ""}
#define aethermesh_AuthResponse_init_default     {0, "", 0}
#define aethermesh_MeshPacket_init_zero          {0, 0, 0, 0, 0, 0, {aethermesh_TextMessage_init_zero}, 0, 0, 0}
#define aethermesh_TextMessage_init_zero         {"", "", 0}
#define aethermesh_Telemetry_init_zero           {0, 0, 0, 0, "", 0, "", 0}
#define aethermesh_RouteDiscovery_init_zero      {_aethermesh_RouteDiscovery_Type_MIN, 0, 0}
#define aethermesh_Ack_init_zero                 {0, 0, 0}
#define aethermesh_NodeConfig_init_zero          {"", 0, 0, 0, 0, 0, 0, 0, 0, ""}
#define aethermesh_AuthRequest_init_zero         {"", 0, ""}
#define aethermesh_AuthResponse_init_zero        {0, "", 0}

/* Field tags (for use in manual encoding/decoding) */
#define aethermesh_TextMessage_content_tag       1
#define aethermesh_TextMessage_channel_tag       2
#define aethermesh_TextMessage_is_encrypted_tag  3
#define aethermesh_Telemetry_battery_level_tag   1
#define aethermesh_Telemetry_latitude_tag        2
#define aethermesh_Telemetry_longitude_tag       3
#define aethermesh_Telemetry_altitude_tag        4
#define aethermesh_Telemetry_node_model_tag      5
#define aethermesh_Telemetry_uptime_seconds_tag  6
#define aethermesh_Telemetry_firmware_version_tag 7
#define aethermesh_Telemetry_is_charging_tag     8
#define aethermesh_RouteDiscovery_type_tag       1
#define aethermesh_RouteDiscovery_target_id_tag  2
#define aethermesh_RouteDiscovery_metric_tag     3
#define aethermesh_Ack_acked_packet_id_tag       1
#define aethermesh_Ack_acked_rx_rssi_tag         2
#define aethermesh_Ack_acked_rx_snr_tag          3
#define aethermesh_NodeConfig_node_name_tag      1
#define aethermesh_NodeConfig_lora_sf_tag        2
#define aethermesh_NodeConfig_lora_bw_tag        3
#define aethermesh_NodeConfig_lora_tx_power_tag  4
#define aethermesh_NodeConfig_region_tag         5
#define aethermesh_NodeConfig_node_role_tag      6
#define aethermesh_NodeConfig_telemetry_interval_tag 7
#define aethermesh_NodeConfig_screen_timeout_secs_tag 8
#define aethermesh_NodeConfig_power_save_mode_tag 9
#define aethermesh_NodeConfig_config_password_tag 10
#define aethermesh_AuthRequest_password_tag      1
#define aethermesh_AuthRequest_is_change_password_tag 2
#define aethermesh_AuthRequest_new_password_tag  3
#define aethermesh_AuthResponse_success_tag      1
#define aethermesh_AuthResponse_message_tag      2
#define aethermesh_AuthResponse_password_not_set_tag 3
#define aethermesh_MeshPacket_sender_id_tag      1
#define aethermesh_MeshPacket_recipient_id_tag   2
#define aethermesh_MeshPacket_packet_id_tag      3
#define aethermesh_MeshPacket_hop_limit_tag      4
#define aethermesh_MeshPacket_want_ack_tag       5
#define aethermesh_MeshPacket_text_tag           6
#define aethermesh_MeshPacket_telemetry_tag      7
#define aethermesh_MeshPacket_route_discovery_tag 8
#define aethermesh_MeshPacket_ack_tag            9
#define aethermesh_MeshPacket_config_tag         11
#define aethermesh_MeshPacket_auth_request_tag   12
#define aethermesh_MeshPacket_auth_response_tag  13
#define aethermesh_MeshPacket_prev_hop_id_tag    10
#define aethermesh_MeshPacket_rx_rssi_tag        14
#define aethermesh_MeshPacket_rx_snr_tag         15

/* Struct field encoding specification for nanopb */
#define aethermesh_MeshPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sender_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   recipient_id,      2) \
X(a, STATIC,   SINGULAR, UINT32,   packet_id,         3) \
X(a, STATIC,   SINGULAR, UINT32,   hop_limit,         4) \
X(a, STATIC,   SINGULAR, BOOL,     want_ack,          5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,text,payload.text),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,telemetry,payload.telemetry),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,route_discovery,payload.route_discovery),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ack,payload.ack),   9) \
X(a, STATIC,   SINGULAR, UINT32,   prev_hop_id,      10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,config,payload.config),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,auth_request,payload.auth_request),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,auth_response,payload.auth_response),  13) \
X(a, STATIC,   SINGULAR, FLOAT,    rx_rssi,          14) \
X(a, STATIC,   SINGULAR, FLOAT,    rx_snr,           15)
#define aethermesh_MeshPacket_CALLBACK NULL
#define aethermesh_MeshPacket_DEFAULT NULL
#define aethermesh_MeshPacket_payload_text_MSGTYPE aethermesh_TextMessage
#define aethermesh_MeshPacket_payload_telemetry_MSGTYPE aethermesh_Telemetry
#define aethermesh_MeshPacket_payload_route_discovery_MSGTYPE aethermesh_RouteDiscovery
#define aethermesh_MeshPacket_payload_ack_MSGTYPE aethermesh_Ack
#define aethermesh_MeshPacket_payload_config_MSGTYPE aethermesh_NodeConfig
#define aethermesh_MeshPacket_payload_auth_request_MSGTYPE aethermesh_AuthRequest
#define aethermesh_MeshPacket_payload_auth_response_MSGTYPE aethermesh_AuthResponse

#define aethermesh_TextMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   content,           1) \
X(a, STATIC,   SINGULAR, STRING,   channel,           2) \
X(a, STATIC,   SINGULAR, BOOL,     is_encrypted,      3)
#define aethermesh_TextMessage_CALLBACK NULL
#define aethermesh_TextMessage_DEFAULT NULL

#define aethermesh_Telemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   battery_level,     1) \
X(a, STATIC,   SINGULAR, FLOAT,    latitude,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    longitude,         3) \
X(a, STATIC,   SINGULAR, INT32,    altitude,          4) \
X(a, STATIC,   SINGULAR, STRING,   node_model,        5) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_seconds,    6) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   7) \
X(a, STATIC,   SINGULAR, BOOL,     is_charging,       8)
#define aethermesh_Telemetry_CALLBACK NULL
#define aethermesh_Telemetry_DEFAULT NULL

#define aethermesh_RouteDiscovery_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   target_id,         2) \
X(a, STATIC,   SINGULAR, UINT32,   metric,            3)
#define aethermesh_RouteDiscovery_CALLBACK NULL
#define aethermesh_RouteDiscovery_DEFAULT NULL

#define aethermesh_Ack_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   acked_packet_id,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    acked_rx_rssi,     2) \
X(a, STATIC,   SINGULAR, FLOAT,    acked_rx_snr,      3)
#define aethermesh_Ack_CALLBACK NULL
#define aethermesh_Ack_DEFAULT NULL

#define aethermesh_NodeConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   node_name,         1) \
X(a, STATIC,   SINGULAR, UINT32,   lora_sf,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    lora_bw,           3) \
X(a, STATIC,   SINGULAR, INT32,    lora_tx_power,     4) \
X(a, STATIC,   SINGULAR, UINT32,   region,            5) \
X(a, STATIC,   SINGULAR, UINT32,   node_role,         6) \
X(a, STATIC,   SINGULAR, UINT32,   telemetry_interval,   7) \
X(a, STATIC,   SINGULAR, UINT32,   screen_timeout_secs,   8) \
X(a, STATIC,   SINGULAR, BOOL,     power_save_mode,   9) \
X(a, STATIC,   SINGULAR, STRING,   config_password,  10)
#define aethermesh_NodeConfig_CALLBACK NULL
#define aethermesh_NodeConfig_DEFAULT NULL

#define aethermesh_AuthRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   password,          1) \
X(a, STATIC,   SINGULAR, BOOL,     is_change_password,   2) \
X(a, STATIC,   SINGULAR, STRING,   new_password,      3)
#define aethermesh_AuthRequest_CALLBACK NULL
#define aethermesh_AuthRequest_DEFAULT NULL

#define aethermesh_AuthResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2) \
X(a, STATIC,   SINGULAR, BOOL,     password_not_set,   3)
#define aethermesh_AuthResponse_CALLBACK NULL
#define aethermesh_AuthResponse_DEFAULT NULL

extern const pb_msgdesc_t aethermesh_MeshPacket_msg;
extern const pb_msgdesc_t aethermesh_TextMessage_msg;
extern const pb_msgdesc_t aethermesh_Telemetry_msg;
extern const pb_msgdesc_t aethermesh_RouteDiscovery_msg;
extern const pb_msgdesc_t aethermesh_Ack_msg;
extern const pb_msgdesc_t aethermesh_NodeConfig_msg;
extern const pb_msgdesc_t aethermesh_AuthRequest_msg;
extern const pb_msgdesc_t aethermesh_AuthResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aethermesh_MeshPacket_fields &aethermesh_MeshPacket_msg
#define aethermesh_TextMessage_fields &aethermesh_TextMessage_msg
#define aethermesh_Telemetry_fields &aethermesh_Telemetry_msg
#define aethermesh_RouteDiscovery_fields &aethermesh_RouteDiscovery_msg
#define aethermesh_Ack_fields &aethermesh_Ack_msg
#define aethermesh_NodeConfig_fields &aethermesh_NodeConfig_msg
#define aethermesh_AuthRequest_fields &aethermesh_AuthRequest_msg
#define aethermesh_AuthResponse_fields &aethermesh_AuthResponse_msg

/* Maximum encoded size of messages (where known) */
#define AETHERMESH_MESH_PB_H_MAX_SIZE            aethermesh_MeshPacket_size
#define aethermesh_Ack_size                      16
#define aethermesh_AuthRequest_size              68
#define aethermesh_AuthResponse_size             37
#define aethermesh_MeshPacket_size               250
#define aethermesh_NodeConfig_size               100
#define aethermesh_RouteDiscovery_size           14
#define aethermesh_Telemetry_size                81
#define aethermesh_TextMessage_size              205

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
