"""Shared board definitions and deterministic app/browser generation."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BOARDS = json.loads((ROOT / "config/boards.json").read_text(encoding="utf-8"))

def generated_files():
    def quote(value):
        return json.dumps(value)
    def aliases(values):
        return "listOf(" + ", ".join(map(quote, values)) + ")"
    lines = []
    for b in BOARDS:
        lines.append("        Board(" + ", ".join([
            quote(b["id"]), quote(b["env"]), quote(b["updateFormat"]),
            aliases(b["modelAliases"]), aliases(b["fileAliases"])
        ]) + "),")
    kotlin = """// Generated by tools/board_registry.py. Edit config/boards.json.
package com.silentwolf75.aethermesh.data

object BoardRegistry {
    data class Board(val id: String, val env: String, val updateFormat: String,
                     val modelAliases: List<String>, val fileAliases: List<String>)
    val boards = listOf(
""" + "\n".join(lines) + """
    )
    private fun normalized(value: String) = value.lowercase().replace('_', '-')
    fun forModel(model: String?): Board? {
        val value = normalized(model.orEmpty())
        return boards.firstOrNull { board -> board.modelAliases.any { alias -> alias.split(" ").all { value.contains(it) } } }
    }
    fun forId(id: String?): Board? = boards.firstOrNull { it.id.equals(id, ignoreCase = true) }
    fun forFile(file: String): Board? {
        val value = normalized(file)
        return boards.firstOrNull { board ->
            value.contains(normalized(board.env)) || board.fileAliases.any { value.contains(it) }
        }
    }
}
"""
    return {
        ROOT / "app/app/src/main/java/com/silentwolf75/aethermesh/data/BoardRegistry.kt": kotlin,
        ROOT / "web-flasher/boards.js": "// Generated by tools/board_registry.py. Edit config/boards.json.\nexport const boards = " + json.dumps(BOARDS, indent=2) + ";\n"
    }

def generate(check=False):
    for path, content in generated_files().items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Stale generated board definitions: {path}. Run python tools/board_registry.py")
        else:
            path.write_text(content, encoding="utf-8")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    generate(parser.parse_args().check)
